### ISSUE TITLE
how to add new spawn area?

### ISSUE THREAD

**Issue by JordanPANDA** [RedEM-RP/redemrp_respawn#10]
Sorry for the maybe "noob" question but, **How can i add a new  spawn area at a location i want in the start of the game ?**

I know it's on the HTML that you can edit the start map spawn etc but i can't manage to make my location work and have red circle on it.

**Comment by amakuu** [comment]
Please do not open new issues with `questions`. Use our discord to ask those kind of things. 
/close

**Comment by amakuu** [comment]
correctly installing redemrp_skin saves skins.
/close
