### ISSUE TITLE
RESPAWN 

### ISSUE THREAD

**Issue by always91** [RedEM-RP/redemrp_respawn#12]
hi i am testing new update but no one creates ped like the old version?
spawn with ped original game

**Comment by Garik0w** [comment]
are u have redmrp_skin?

**Comment by patcallahan** [comment]
im having the same issue, i recently installed a RedM server with all these mods and redemrp_skin isnt doing anything, neither is redemrp_clothing. Whenever i make a new character i just get the default ped and thats it (arthur).

**Comment by iJaydenJay** [comment]
I am having the same error

**Comment by HalconBM** [comment]
Same problem here. Since the last update the redemrp_skin does not work. You appear with Arthur's skin. Thanks for the daily effort to improve this type of script

**Comment by CryptoGenics** [comment]
Should now be resolved ^

**Comment by HalconBM** [comment]
> Should now be resolved ^

You are the best!
