### ISSUE TITLE
respawn problem

### ISSUE THREAD

**Issue by PokeSer** [RedEM-RP/redemrp_respawn#4]
Hi, I don't know if it's a mistake but when you die you reappear before the counter reaches 0.

**Comment by BlueberryRP** [comment]
same problem. Sometimes when player die then rise before the counter reaches 0. Without /respawn command.

**Comment by amakuu** [comment]
u mean player is respawning? or just player model is showing 1 sec before selecting screen?

**Comment by PokeSer** [comment]
Example: 
![dead](https://user-images.githubusercontent.com/47903164/70922310-2a5ff800-2026-11ea-8d95-c30d8da97675.png)

**Comment by BlueberryRP** [comment]
And you can walk and do anything.

**Comment by diegobh** [comment]
Disable the loading of spawnmanager and you will be good. It is NOT this resource fault..

E.g: server.cfg

#ensure spawnmanager

**Comment by amakuu** [comment]
It should work properly with spawnmanager, we must figure out what we have to do to make it compatible with spawnmanager.
/close
